spring:
  profiles: default
  datasource:
    max-active: 2
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: local
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
---
spring:
  profiles: cloud
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
management:
  cloudfoundry:
    skip-ssl-validation: true


